1:
    На вершине иерархии исключений находится класс Exception.

2:
    Как используются ключевые слова try и catch:
    В try происходит возникновение ошибки.
    В catch идет обработка этой ошибки (вывод сообщения, остановка выполнения и др.)

3:
    Ошибка: что бы catch сработал, фрагмент кода с обращением в массив нужно обернуть в блок try {}

4:
    Если исключение не будет перехвачено, его перехватит JVM и прекратит работу всей программы.

5:
    Ошибка: try и catch должны находится внутри метода.

6:
    Да, внутренний блок catch может повторно сгенерировать исключение,
    которое будет обработано во внешнем блоке catch.

7:
    Нет, блок finally это не последний фрагмент кода, выполняемый перед завершением программы.
    Блок finally выполняется всегда после выполнения блока try.

8:
    Проверяемые исключения необходимо явно объявлять
    с помощью инструкции throws, включаемой в объявление метода.

9:
    Ошибка: класс не определяется как производнй от класса Exception,
    необходимо указать: extends Exception.


10:
    StackDemo.java

11:

12:

13:

14: